# This is run when starting a Gitpod workspace on this repository

image:
  file: .docker/gitpod/Dockerfile

vscode:
  extensions:
    - leanprover.lean4 # install the Lean 4 VS Code extension

tasks:
  - command: curl 'https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh' -sSf | sh -s -- -y --default-toolchain none
  - command: elan toolchain install $(cat lean-toolchain)
  - command: lake exe cache get
  - command: lake build
  #- command: . /home/gitpod/.profile && lake exe cache get # Download cache

